# Argo Events - Production overrides

controller:
  serviceAccount:
    labels:
      azure.workload.identity/use: "true"
    annotations:
      azure.workload.identity/client-id: "4680cf05-618a-4536-be68-2594fb8fd2a6"
