# Grafana Agent - Dev overrides

serviceAccount:
  annotations:
    azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"

extraEnv:
  - name: AMW_REMOTE_WRITE_URL
    value: "https://dev-aks-amw.westus2.prometheus.monitor.azure.com/api/v1/write"
  - name: CLUSTER_NAME
    value: "dev-aks"
