# Loki - Production overrides
# Production: longer retention, larger storage

serviceAccount:
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "59c7fd7e-dafc-4648-b6fe-358aa6c8e71e"

loki:
  commonConfig:
    replication_factor: 1
  limits_config:
    retention_period: 2160h

singleBinary:
  persistence:
    size: 100Gi
