# KEDA - prod env overrides

serviceAccount:
  operator:
    labels:
      azure.workload.identity/use: "true"
    annotations:
      azure.workload.identity/client-id: "f67584d6-7ab2-4987-8353-99c29d712699"

podDisruptionBudget:
  operator:
    minAvailable: 1
  metricServer:
    minAvailable: 1
  webhooks:
    minAvailable: 1
