# Argo Workflows - prod env overrides

server:
  serviceAccount:
    labels:
      azure.workload.identity/use: "true"
    annotations:
      azure.workload.identity/client-id: "c904d66e-7965-433b-a858-b9922826ba28"

artifactRepository:
  azure:
    endpoint: https://prodaksartifacts8391ac17.blob.core.windows.net
    container: argo-artifacts
